[main]
  serialize = "{version}-{banner}"
  tag = false
  version = "4.2.0"

[[operate]]
  location = "main.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""

[[operate]]
  location = "cmd/selfupdate.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""

[[operate]]
  location = "releases/build.bat"
  replace = "version-helper-{}\""
  search = "version-helper-{}\""

[[operate]]
  location = "README.md"
  replace = "# Version-Helper-{}"
  search = "# Version-Helper-{}"