[main]
  tag = true
  version = "2.1.0"

[[operate]]
  location = "main.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""

[[operate]]
  location = "releases/build.bat"
  replace = "version-helper-{}\""
  search = "version-helper-{}\""

[[operate]]
  location = "README.md"
  replace = "# Version-Helper-{}"
  search = "# Version-Helper-{}"