[main]
serialize     = "{version}-{banner}"
tag           = true
extraCommands = []
version       = "4.4.1"

[[operate]]
location = "main.go"
replace  = "__version__ = \"{}\""
search   = "__version__ = \"{}\""

[[operate]]
location = "cmd/selfupdate.go"
replace  = "__version__ = \"{}\""
search   = "__version__ = \"{}\""

[[operate]]
location = "README.md"
replace  = "# Version-Helper-{}"
search   = "# Version-Helper-{}"
