[main]
  tag = false
  version = "1.0.2"

[[operate]]
  location = "main.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""

[[operate]]
  location = "releases/build.bat"
  replace = "version-helper-{}\""
  search = "version-helper-{}\""

[[operate]]
  location = "README.md"
  replace = "\*\*\*version {}\*\*\*"
  search = "\*\*\*version {}\*\*\*"